# Generated by Django 4.1.3 on 2023-06-23 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_items',
            name='products',
        ),
        migrations.AddField(
            model_name='order_items',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='customer.products'),
        ),
    ]
