# Generated by Django 4.1.3 on 2023-06-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_order_items_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
