# Generated by Django 4.1.3 on 2023-06-24 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customer_profile_payment_method'),
        ('customer', '0008_shipping_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_address',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.customer_profile'),
        ),
    ]
