# Generated by Django 4.1.3 on 2023-06-24 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_shipping_address_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping_address',
            name='customer',
        ),
        migrations.AddField(
            model_name='shipping_address',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='customer.order_items'),
        ),
    ]
