# Generated by Django 4.1.3 on 2023-06-24 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_remove_shipping_address_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping_address',
            name='order_item',
        ),
        migrations.AddField(
            model_name='shipping_address',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='customer.order'),
        ),
    ]
