# Generated by Django 4.1.3 on 2023-06-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='billing_address',
            field=models.CharField(blank=True, choices=[('SHIPPING_ADDRESS', 'same as shipping address'), ('DIFFERENT', 'different billing address')], max_length=200, null=True),
        ),
    ]
