# Generated by Django 4.1.3 on 2023-06-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_order_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_history',
        ),
    ]
