# Generated by Django 4.1.3 on 2023-06-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_delete_order_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date_ordered',), 'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='order_items',
            options={'ordering': ('-date_added',), 'verbose_name_plural': 'Order_items'},
        ),
    ]
