# Generated by Django 4.1.3 on 2023-06-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_order_options_alter_order_items_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='selected',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
