# Generated by Django 4.1.3 on 2023-06-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_alter_order_items_order_alter_payment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(True), related_name='order_item', to='customer.order'),
        ),
    ]
