# Generated by Django 4.1.3 on 2023-07-04 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_order_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_history',
            options={'ordering': ('-date_ordered',), 'verbose_name_plural': 'Order_history'},
        ),
        migrations.RenameField(
            model_name='order_history',
            old_name='date_added',
            new_name='date_ordered',
        ),
        migrations.RemoveField(
            model_name='order_history',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order_history',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order_history',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order_history',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Order_items_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order_history')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.products')),
            ],
            options={
                'verbose_name_plural': 'Order_items_history',
            },
        ),
    ]
