# Generated by Django 4.1.3 on 2023-07-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_shipping_address_order_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=11, unique=True),
        ),
    ]
