# Generated by Django 4.1.3 on 2023-07-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_alter_customer_profile_payment_method'),
        ('customer', '0029_alter_order_items_history_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_history',
            name='total_order_items',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order_history',
            name='customer',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='authentication.customer_profile'),
        ),
        migrations.AlterField(
            model_name='order_history',
            name='order_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order_history',
            name='total_price',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order_items_history',
            name='order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='order_items_history', to='customer.order_history'),
        ),
        migrations.AlterField(
            model_name='order_items_history',
            name='price',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='order_items_history',
            name='product',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='customer.products'),
        ),
        migrations.AlterField(
            model_name='order_items_history',
            name='quantity',
            field=models.IntegerField(editable=False),
        ),
    ]
