# Generated by Django 4.1.3 on 2023-07-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_order_history_total_order_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
    ]
