# Generated by Django 4.1.3 on 2023-07-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_alter_order_items_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
