# Generated by Django 4.2.3 on 2023-07-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_history',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
