# Generated by Django 4.2.3 on 2023-07-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_management', '0002_alter_order_history_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_history',
            name='order_id',
            field=models.CharField(editable=False, max_length=11, unique=True),
        ),
    ]
